/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManagementSystem;

/**
 *
 * @author group
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ManageCategoriesButton = new javax.swing.JLabel();
        CheckReportsButton = new javax.swing.JLabel();
        ManageEmployeesButton = new javax.swing.JLabel();
        ManageOrdersButton = new javax.swing.JLabel();
        ManageProductsButton = new javax.swing.JLabel();
        Categories = new javax.swing.JLabel();
        Employees = new javax.swing.JLabel();
        Orders = new javax.swing.JLabel();
        Products = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JLabel();
        Reports = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        ManageCategoriesButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        ManageCategoriesButton.setForeground(new java.awt.Color(0, 0, 102));
        ManageCategoriesButton.setText("Manage Categories");
        ManageCategoriesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCategoriesButtonMouseClicked(evt);
            }
        });

        CheckReportsButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        CheckReportsButton.setForeground(new java.awt.Color(0, 0, 102));
        CheckReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckReportsButton.setText("Check Reports       ");
        CheckReportsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckReportsButtonMouseClicked(evt);
            }
        });

        ManageEmployeesButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        ManageEmployeesButton.setForeground(new java.awt.Color(0, 0, 102));
        ManageEmployeesButton.setText("Manage Employee");
        ManageEmployeesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageEmployeesButtonMouseClicked(evt);
            }
        });

        ManageOrdersButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        ManageOrdersButton.setForeground(new java.awt.Color(0, 0, 102));
        ManageOrdersButton.setText("Manage Orders");
        ManageOrdersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageOrdersButtonMouseClicked(evt);
            }
        });

        ManageProductsButton.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        ManageProductsButton.setForeground(new java.awt.Color(0, 0, 102));
        ManageProductsButton.setText("Manage Products");
        ManageProductsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageProductsButtonMouseClicked(evt);
            }
        });

        Categories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catg.jpg"))); // NOI18N
        Categories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriesMouseClicked(evt);
            }
        });

        Employees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mangemp.png"))); // NOI18N
        Employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeesMouseClicked(evt);
            }
        });

        Orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersMouseClicked(evt);
            }
        });

        Products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rep.jpg"))); // NOI18N
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsMouseClicked(evt);
            }
        });

        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown.png"))); // NOI18N
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutButton.setText("Log Out");
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });

        Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chkrep.jpg"))); // NOI18N
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Orders)
                        .addGap(168, 168, 168)
                        .addComponent(Products)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(ManageOrdersButton)
                        .addGap(96, 96, 96)
                        .addComponent(ManageProductsButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(77, Short.MAX_VALUE)
                                .addComponent(ManageCategoriesButton)
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(Categories, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CheckReportsButton)
                                .addGap(30, 30, 30)
                                .addComponent(ManageEmployeesButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(Reports)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Employees)
                                .addGap(60, 60, 60)))))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LogOut)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LogOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(Categories))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Employees)
                            .addComponent(Reports))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ManageCategoriesButton)
                            .addComponent(ManageEmployeesButton)
                            .addComponent(CheckReportsButton))
                        .addGap(35, 35, 35)
                        .addComponent(Products))
                    .addComponent(Orders))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageProductsButton)
                    .addComponent(ManageOrdersButton))
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
        
    }//GEN-LAST:event_LogOutMouseClicked

    private void CategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriesMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        new Categories().setVisible(true);
        
    }//GEN-LAST:event_CategoriesMouseClicked

    private void ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Reports().setVisible(true);
    }//GEN-LAST:event_ReportsMouseClicked

    private void EmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeesMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Employees().setVisible(true);
    }//GEN-LAST:event_EmployeesMouseClicked

    private void OrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
        new Cashier().setVisible(true);
    }//GEN-LAST:event_OrdersMouseClicked

    private void ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Products().setVisible(true);
    }//GEN-LAST:event_ProductsMouseClicked

    private void ManageCategoriesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCategoriesButtonMouseClicked
       this.setVisible(false);
        new Categories().setVisible(true);
    }//GEN-LAST:event_ManageCategoriesButtonMouseClicked

    private void CheckReportsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckReportsButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Reports().setVisible(true);
    }//GEN-LAST:event_CheckReportsButtonMouseClicked

    private void ManageEmployeesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageEmployeesButtonMouseClicked
        this.setVisible(false);
        new Employees().setVisible(true);
    }//GEN-LAST:event_ManageEmployeesButtonMouseClicked

    private void ManageOrdersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageOrdersButtonMouseClicked
        this.setVisible(false);
        new Cashier().setVisible(true);
    }//GEN-LAST:event_ManageOrdersButtonMouseClicked

    private void ManageProductsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProductsButtonMouseClicked
        this.setVisible(false);
        new Products().setVisible(true);
    }//GEN-LAST:event_ManageProductsButtonMouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categories;
    private javax.swing.JLabel CheckReportsButton;
    private javax.swing.JLabel Employees;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JLabel ManageCategoriesButton;
    private javax.swing.JLabel ManageEmployeesButton;
    private javax.swing.JLabel ManageOrdersButton;
    private javax.swing.JLabel ManageProductsButton;
    private javax.swing.JLabel Orders;
    private javax.swing.JLabel Products;
    private javax.swing.JLabel Reports;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
